// Auto-generated by tools/rule-pack-generator/src/keypair.ts.
// Replace this if you rotate keys. Run `pnpm gen:keypair` and copy keypair.out/pubkey.ts.
// SECURITY: never commit the matching private key.
export const RULE_PACK_PUBLIC_KEY_B64 =
  'MCowBQYDK2VwAyEA7X43zyokhJXdyqiYljLFhdgYFAHT6vtDRaYhtFgViqc=';

// Update URL points at the rule-pack-latest GitHub release manifest.
// Workflow at .github/workflows/rule-pack-publish.yml refreshes this asset.
export const RULE_PACK_UPDATE_URL =
  'https://github.com/tdube-architech/VibeOps/releases/download/rule-pack-latest/latest.json';
